name: Random Reviewer Discord
description: Automatically assign reviewers at random and notify them on Discord
author: JedBeom

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: user-check
  color: green

# Define your inputs here.
inputs:
  candidates:
    description: candidates of reviewers. see .env.example.
    required: true
  webhook_url:
    description: Discord webhook url
    required: true
  template:
    description: Message template used whenever the reviewer is assigned.
    required: false
  pulls_min_age:
    description: (in hours) Pulls which are not old by the specified amount of time are ignored when review reminding.
    required: false
    default: 2

runs:
  using: node20
  main: dist/index.js
