name: Random Reviewer with Discord
description: randomly assigns reviewers to PRs and alert using Discord.
author: JedBeom

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: "1000"

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node22
  main: dist/index.js
