name: Random Reviewer Discord

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - review_requested
    branches:
      - main
  pull_request_review:
    types:
      - submitted
  schedule:
    - cron: 0 10 * * 6
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Run random-reviewer-discord
        uses: JedBeom/random-reviewer-discord@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          usernames: ${{ secrets.USERNAMES }}
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          schedule_prs_min_age: 24
          show_discord_link_preview: false
          notify_review_requested_on_closed: false
          notify_review_requested_on_draft: false
          # template_opened: >-
          # template_reopened_assigned: >-
          # template_reopened_exist_one: >-
          # template_reopened_exist_plural: >-
          # template_ready_for_review_assigned: >-
          # template_ready_for_review_exist_one: >-
          # template_ready_for_review_exist_plural: >-
          # template_review_requested_one: >-
          # template_review_requested_plural: >-
          # template_schedule: >-
          # template_review_submitted_commented: >-
          # template_review_submitted_changes_requested: >-
          # template_review_submitted_approved: >-
